spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatdb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: sukim2919@

  jpa:
    hibernate:
      ddl-auto: update   # create, update, validate, none 중 선택 가능

logging:
  file:
    name: ./logs/chatApp.log